### ISSUE TITLE
error 500 (/v1/dashboard/side_dishes) in updating photo

### ISSUE THREAD

**Issue by Mahdiye** [geekhouseteam/yumbox#15]
TypeError: Cannot read property 'filename' of undefined
  at get_ext (/home/mahdie/Projects/yumbox/api/src/methods/file.coffee:22:16)
  at Object.save (/home/mahdie/Projects/yumbox/api/src/methods/file.coffee:40:12)
  at SideDish.Base.save_image (/home/mahdie/Projects/yumbox/api/src/methods/model.coffee:66:28)
  at SideDish._save_photo (/home/mahdie/Projects/yumbox/meals/src/models/side_dish.coffee:58:8)
  at SideDish.after_save (/home/mahdie/Projects/yumbox/meals/src/models/side_dish.coffee:37:8)
  at SideDish.<anonymous> (/home/mahdie/Projects/yumbox/api/node_modules/odme/build/cb.js:156:28)
  at _fulfilled (/home/mahdie/Projects/yumbox/api/node_modules/q/q.js:834:54)
  at self.promiseDispatch.done (/home/mahdie/Projects/yumbox/api/node_modules/q/q.js:863:30)
  at Promise.promise.promiseDispatch (/home/mahdie/Projects/yumbox/api/node_modules/q/q.js:796:13)
  at /home/mahdie/Projects/yumbox/api/node_modules/q/q.js:604:44
  at runSingle (/home/mahdie/Projects/yumbox/api/node_modules/q/q.js:137:13)
  at flush (/home/mahdie/Projects/yumbox/api/node_modules/q/q.js:125:13)
  at nextTickCallbackWith0Args (node.js:419:9)
  at process._tickDomainCallback (node.js:389:13)

**Comment by Mahdiye** [comment]
payload should be stream in put side dish route

+        payload:
+          output: 'stream'
